{
 "title": "Ghost Node stats",
 "description": "Monitor your Ghost core node and aspects of the network.",
 "tags": [ "bitcoin" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Basic network stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Creation Rate",
     "type": "graph",
     "description": "Number of blocks created per day using different trailing rates.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "floor(sum(rate(bitcoin_blocks[3h])) * 3600 * 24)",
       "legendFormat": "3h"
      },
      {
       "expr": "floor(sum(rate(bitcoin_blocks[6h])) * 3600 * 24)",
       "legendFormat": "6h"
      },
      {
       "expr": "floor(sum(rate(bitcoin_blocks[12h])) * 3600 * 24)",
       "legendFormat": "12h"
      },
      {
       "expr": "floor(sum(rate(bitcoin_blocks[7d])) * 3600 * 24)",
       "legendFormat": "7d"
      }
     ]
    },
    {
     "title": "Network Hash Rate",
     "type": "graph",
     "description": "Estimated network hashes per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avg(bitcoin_hashps)", "legendFormat": "120-blocks" },
      { "expr": "avg(bitcoin_hashps_neg1)", "legendFormat": "last-difficulty" }
     ]
    },
    {
     "title": "Chain Branches",
     "type": "graph",
     "description": "Number of tips seen in the chain.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avg(bitcoin_num_chaintips)", "legendFormat": "tips" }
     ]
    },
    {
     "title": "Network traffic",
     "type": "graph",
     "description": "Sent and received traffic rates",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(bitcoin_total_bytes_sent[5m]))",
       "legendFormat": "sent"
      },
      {
       "expr": "-sum(irate(bitcoin_total_bytes_recv[10m]))",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "Estimated Fee",
     "type": "graph",
     "description": "The estimated smart fee for confirmation of transactions in a given number of blocks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avg(bitcoin_est_smart_fee_2)", "legendFormat": "2-blocks" },
      { "expr": "avg(bitcoin_est_smart_fee_20)", "legendFormat": "20-blocks" },
      { "expr": "avg(bitcoin_est_smart_fee_3)", "legendFormat": "3-blocks" },
      { "expr": "avg(bitcoin_est_smart_fee_5)", "legendFormat": "5-blocks" }
     ]
    },
    {
     "title": "Peers",
     "type": "graph",
     "description": "Number of peers that have been banned and the reason for the ban.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "count(bitcoin_banned_until) by (reason)",
       "legendFormat": "ban - {{ reason }}"
      },
      { "expr": "sum(bitcoin_peers)", "legendFormat": "peers" }
     ]
    }
   ]
  },
  {
   "title": "Staking & Supply",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GHOST Supply",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitcoin_supply", "legendFormat": "GHOST" }
     ]
    },
    {
     "title": "NetStake",
     "type": "stat",
     "description": "Current percent of supply staking\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "bitcoin_netstake_perc" }
     ]
    },
    {
     "title": "Difficulty",
     "type": "graph",
     "description": "Difficulty value",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avg(bitcoin_difficulty)", "legendFormat": "difficulty" }
     ]
    },
    {
     "title": "Ghost network stakeweight",
     "type": "graph",
     "description": "Estimated coins staking",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitcoin_network_stakeweight", "legendFormat": "GHOST" }
     ]
    },
    {
     "title": "Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitcoin_latest_block_height", "legendFormat": "Blocks" }
     ]
    }
   ]
  },
  {
   "title": "Transactions stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UTXOS",
     "type": "graph",
     "description": "UTXO Count of GHOST Network\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitcoin_utxos", "legendFormat": "GHOST UTXOS" }
     ]
    },
    {
     "title": "Blinded UTXOS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitcoin_utxos_blinded", "legendFormat": "UTXOS" }
     ]
    },
    {
     "title": "Mempool TXes",
     "type": "graph",
     "description": "Transactions in mempool\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitcoin_mempool_size", "legendFormat": "Mempool TXes" }
     ]
    },
    {
     "title": "Block value",
     "type": "graph",
     "description": "Value of the block transactions in GHOST.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bitcoin_latest_block_value)",
       "legendFormat": "GHOST"
      }
     ]
    }
   ]
  }
 ]
}